services:
  db:
    image: mysql:8
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: Huhtikuu2026!
      MYSQL_DATABASE: cms
      MYSQL_USER: quiz_user
      MYSQL_PASSWORD: Huhtikuu2026!

    ports:
      - "3306:3306"
    volumes:
        - db_data:/var/lib/mysql
    healthcheck:
          test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
          interval: 5s
          timeout: 3s
          retries: 10
  app:
    build: .
    restart: unless-stopped
    ports:
      - "3000:3000"
    env_file:
        - .env
    depends_on:
      db:
        condition: service_healthy
    volumes:
    - uploads:/app/public/uploads
volumes:
  db_data:
  uploads: 